service: serverless-rest-api

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello-world:
    handler: handler.helloWorld
    events:
      - http:
          path: hello-world
          method: post
          cors: true